### ISSUE TITLE
aggregate_dictionary_distributed_keys.txt tabbing

### ISSUE THREAD

**Issue by itslily88** [mac4n6/APOLLO#1]
For some reason with "aggregate_dictionary_distributed_keys.txt", I had to tab over everything from "select" to the end of the statement. Running windows 10, python 2.7, cmd as admin. It kept crashing on that module (immediately). When I removed that module, it ran no issues. I noticed that the other modules had everything from "select" down tabbed over 1 more spot. I applied that tabbing to "aggregate_dictionary_distributed_keys.txt" and it ran just fine.

**Comment by Greenoak4n6** [comment]
Yep, I had to do the same. Works fine after. I should read here next time before finding the problem. Was going to report it and saw this comment.

**Comment by mac4n6** [comment]
My bad! Fixed
