### ISSUE TITLE
No module named 'ConfigParser'

### ISSUE THREAD

**Issue by yani1shu** [mac4n6/APOLLO#2]
When i try to run the script i get the following message:

 File ".\apollo.py", line 34, in <module>
    from ConfigParser import RawConfigParser
ImportError: No module named 'ConfigParser'

Should there be a module named ConfigParser in the modules folder?

**Comment by mac4n6** [comment]
What version of python are you running?

**Comment by yani1shu** [comment]
3.5.2

I will try running in version 2

**Comment by yani1shu** [comment]
that was the problem. Thanks for the quick response Sarah. Amazing toolset!

**Comment by mac4n6** [comment]
Glad it was just that! I'll update the README to specify, thanks for giving it a try!

**Comment by yani1shu** [comment]
This might be a silly question but when i run the script it's only finding a single database file, the healthdb_secure.sqlite. I'v run Apollo against the extracted TAR, the exported "logical" file system from Cellebrite, and the individual database files exported from Cellebrite. the "logical" file system, that is the one that has a folder structure and the individual database files both resulted in just the single database file being found. The extracted TAR didn't return anything.

Am i missing something?

**Comment by mac4n6** [comment]
It’s not a full file system dump, most of the good stuff isn’t backed up by logical backups.

**Comment by yani1shu** [comment]
Got it! Thank you!!
