### ISSUE TITLE
Errors Running

### ISSUE THREAD

**Issue by lordspazmonkey** [mac4n6/APOLLO#4]
I am receiving the following errors when trying to run this in Python 2.7, I have navigated to the folder containing the Apollo script and the modules have been placed in a Modules folder and the database files I want to run against are in the DBFiles folder. I'm tearing my hair out trying to figure out what i'm doing wrong!

C:\Users\Technicians\Desktop\PythonProgramming\Test>C:\Python27\python.exe apollo.py -o csv -p ios -v 11 Modules DBFiles
Parsing Modules...
Traceback (most recent call last):
  File "apollo.py", line 194, in <module>
    parse_module_definition(mod_info)
  File "apollo.py", line 45, in parse_module_definition
    parser.read(mod_def)
  File "C:\Python27\lib\ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "C:\Python27\lib\ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: Modules\powerlog_accessory_connection.txt, line: 7
'<!DOCTYPE html>\n'

**Comment by lordspazmonkey** [comment]
Solved (kinda) - added the entire modules folder to the folder that contains apollo and ran again and it works. Now however when i try to run again on a different computer under the same conditions (fresh install laptop and Python 2.7 installed) i get errors saying it could not parse the database. Possibly due to file permissions or changes in the database schema

**Comment by mac4n6** [comment]
Can you provide the output that has the errors and the commands used to run the script?
